//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otel_Uygulamasi {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Otel_Uygulamasi.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Bu türü kesin olarak belirtilmiş kaynak sınıfını kullanarak geçerli iş parçacığının
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Açıklama boş olamaz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string aciklamaBosGecilemez {
            get {
                return ResourceManager.GetString("aciklamaBosGecilemez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ardunio Bağlı Değil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ArdunioBagliDegil {
            get {
                return ResourceManager.GetString("ArdunioBagliDegil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ardunio Sıcaklık Bağlantı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ArdunioSicaklinBaglanti {
            get {
                return ResourceManager.GetString("ArdunioSicaklinBaglanti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başarılı bir şekilde check-in yapılmıştır benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BasariliCheckin {
            get {
                return ResourceManager.GetString("BasariliCheckin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başlangıç Zamanı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string baslangicZamani {
            get {
                return ResourceManager.GetString("baslangicZamani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blok Ayarları benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string blokAyarlari {
            get {
                return ResourceManager.GetString("blokAyarlari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blok başarılı bir şekilde düzenlenmiştir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BlokDuzenlendi {
            get {
                return ResourceManager.GetString("BlokDuzenlendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blok başarılı bir şekilde eklenmiştir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Blokeklendi {
            get {
                return ResourceManager.GetString("Blokeklendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen bir blok seçiniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string blokIsmiBosGecilmez {
            get {
                return ResourceManager.GetString("blokIsmiBosGecilmez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blok ismi boş geçilemez. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BlokismiBosOlamaz {
            get {
                return ResourceManager.GetString("BlokismiBosOlamaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blok başarılı bir şekilde silinmiştir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BlokSilmeBasarili {
            get {
                return ResourceManager.GetString("BlokSilmeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen önce blokta bulunan katları siliniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string bloktaBulunanKatlarıSilin {
            get {
                return ResourceManager.GetString("bloktaBulunanKatlarıSilin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Boş Odalar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BosOdalar {
            get {
                return ResourceManager.GetString("BosOdalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Destek benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string btnDestek {
            get {
                return ResourceManager.GetString("btnDestek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string btnEkle {
            get {
                return ResourceManager.GetString("btnEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filtrele benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string btnFiltrele {
            get {
                return ResourceManager.GetString("btnFiltrele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Giriş benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string btnGiris {
            get {
                return ResourceManager.GetString("btnGiris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gönder benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string btnGonder {
            get {
                return ResourceManager.GetString("btnGonder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Görevlendir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string btnGorevlendir {
            get {
                return ResourceManager.GetString("btnGorevlendir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Görevlendirme benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string btnGorevlendirme {
            get {
                return ResourceManager.GetString("btnGorevlendirme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gözat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string btnGozat {
            get {
                return ResourceManager.GetString("btnGozat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İptal benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string btnIptal {
            get {
                return ResourceManager.GetString("btnIptal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kapat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string btnKapat {
            get {
                return ResourceManager.GetString("btnKapat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kat Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string btnKatEkle {
            get {
                return ResourceManager.GetString("btnKatEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kaydet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string btnKaydet {
            get {
                return ResourceManager.GetString("btnKaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Klavye aç benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string btnKlavyeAc {
            get {
                return ResourceManager.GetString("btnKlavyeAc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Onayla benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string btnOnayla {
            get {
                return ResourceManager.GetString("btnOnayla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seçenekler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string btnSecenekler {
            get {
                return ResourceManager.GetString("btnSecenekler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temizle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string btnTemizle {
            get {
                return ResourceManager.GetString("btnTemizle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tüm Personeller benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string chechBoxTümPersoneller {
            get {
                return ResourceManager.GetString("chechBoxTümPersoneller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Özel Gönderim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CheckBoxOzelGonderim {
            get {
                return ResourceManager.GetString("CheckBoxOzelGonderim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check-in Yap benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string checkinYap {
            get {
                return ResourceManager.GetString("checkinYap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check-out işlemi başarı ile tamamlanmıştır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CheckoutBasarili {
            get {
                return ResourceManager.GetString("CheckoutBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check-out işlemi için önce bir kayıt seçiniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string checkoutKayitSec {
            get {
                return ResourceManager.GetString("checkoutKayitSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı adı ve şifremi hatırla benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string chHatirla {
            get {
                return ResourceManager.GetString("chHatirla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çift Kişilik Yatak Sayısı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CiftKisilikYatakSayisi {
            get {
                return ResourceManager.GetString("CiftKisilikYatakSayisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çıkış Tarihi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CikisTarihi {
            get {
                return ResourceManager.GetString("CikisTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çıkış tarihi uzatıldı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string cikisTarihiUzatıldı {
            get {
                return ResourceManager.GetString("cikisTarihiUzatıldı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duyuru Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string duyuruEkle {
            get {
                return ResourceManager.GetString("duyuruEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duyuru başarılı bir şekilde eklenmiştir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DuyuruEklemeBasarili {
            get {
                return ResourceManager.GetString("DuyuruEklemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başarılı bir şekilde duyuru geri alınmıştır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DuyuruGerialmaBasarili {
            get {
                return ResourceManager.GetString("DuyuruGerialmaBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duyuru başarılı bir şekilde güncellenmiştir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DuyuruGuncellemeBasarili {
            get {
                return ResourceManager.GetString("DuyuruGuncellemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duyuru Listesi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string duyuruListesi {
            get {
                return ResourceManager.GetString("duyuruListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başarılı bir şekilde duyuru silinmiştir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DuyuruSilmeBasarili {
            get {
                return ResourceManager.GetString("DuyuruSilmeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Düzenle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Duzenle {
            get {
                return ResourceManager.GetString("Duzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Düzenlemek için blok seçmelisiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DuzenlemekIcınBlokSec {
            get {
                return ResourceManager.GetString("DuzenlemekIcınBlokSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen önce düzenlemek {0}istediğiniz duyuruyu seçiniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DuzenlemekicinDuyuruSec {
            get {
                return ResourceManager.GetString("DuzenlemekicinDuyuruSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Düzenlemek için lütfen bir oda seçiniz ve ardından düzenle tuşuna basınız. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string duzenlemekIcınOdaSec {
            get {
                return ResourceManager.GetString("duzenlemekIcınOdaSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen önce düzenlenecek etkinliği seçiniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string duzenlenecekEtkinlikSecin {
            get {
                return ResourceManager.GetString("duzenlenecekEtkinlikSecin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Düzenlenecek havuzu seçiniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DuzenlenecekHavuzSec {
            get {
                return ResourceManager.GetString("DuzenlenecekHavuzSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen önce düzenlenecek katı seçiniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string DuzenlenecekKatSec {
            get {
                return ResourceManager.GetString("DuzenlenecekKatSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen önce düzenlenecek personeli seçiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string duzenlenecekPersonelSec {
            get {
                return ResourceManager.GetString("duzenlenecekPersonelSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eklenecek gün sayısı pozitif olmalıdır benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string eklenecekGunSayisiPozitifHata {
            get {
                return ResourceManager.GetString("eklenecekGunSayisiPozitifHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen check-in bilgilerini kontrol ediniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string EksikCheckinBilgisi {
            get {
                return ResourceManager.GetString("EksikCheckinBilgisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Etkinlik bilgilerini eksiksiz bir şekilde girdiğinizden emin olunuz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string EksikEtkinlikBilgileri {
            get {
                return ResourceManager.GetString("EksikEtkinlikBilgileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rezervasyon bilgilerinizi lütfen kontrol ediniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string EksikRezervasyonBilgisi {
            get {
                return ResourceManager.GetString("EksikRezervasyonBilgisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen geçerli bir e-mail adresi giriniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string eMailHata {
            get {
                return ResourceManager.GetString("eMailHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Etkinlik Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string etkinlikEkle {
            get {
                return ResourceManager.GetString("etkinlikEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başarılı bir şekilde etkinlik eklenmiştir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string EtkinlikEklemeBasarili {
            get {
                return ResourceManager.GetString("EtkinlikEklemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Etkinlik başarılı bir şekilde geri alınmıştır benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string etkinlikGeriAlmaBasarili {
            get {
                return ResourceManager.GetString("etkinlikGeriAlmaBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başarılı bir şekilde etkinlik güncellenmiştir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string EtkinlikGuncellemeBasarili {
            get {
                return ResourceManager.GetString("EtkinlikGuncellemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Etkinlik Listesi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string etkinlikListesi {
            get {
                return ResourceManager.GetString("etkinlikListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Etkinlik başarılı bir şekilde silinmiştir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string etkinlikSilinmistir {
            get {
                return ResourceManager.GetString("etkinlikSilinmistir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Evet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Evet {
            get {
                return ResourceManager.GetString("Evet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen geri alınacak duyuruyu seçiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GeriAlinacakDuyuruSec {
            get {
                return ResourceManager.GetString("GeriAlinacakDuyuruSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geri Alınacak Etkinlik Seçiniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GeriAlinacakEtkinlikSec {
            get {
                return ResourceManager.GetString("GeriAlinacakEtkinlikSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen önce geri almak istediğiniz etkinliği seçiniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string geriAlinacakEtkinlikSeciniz {
            get {
                return ResourceManager.GetString("geriAlinacakEtkinlikSeciniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen geri almak istediğiniz katı seçiniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string geriAlinacakKatiSecin {
            get {
                return ResourceManager.GetString("geriAlinacakKatiSecin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen önce geri alınacak odayı seçin benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string geriAlinacakOdayiSecin {
            get {
                return ResourceManager.GetString("geriAlinacakOdayiSecin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Giriş Tarihi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GirisTarihi {
            get {
                return ResourceManager.GetString("GirisTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Güncellenemedi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Guncellenemedi {
            get {
                return ResourceManager.GetString("Guncellenemedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gün Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string gunEkle {
            get {
                return ResourceManager.GetString("gunEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eklenecek Gün Sayısı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GunSayisi {
            get {
                return ResourceManager.GetString("GunSayisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı adı ya da şifre hatalıdır benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string HataliKullaniciAdiSifre {
            get {
                return ResourceManager.GetString("HataliKullaniciAdiSifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Havuz Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string HavuzAdi {
            get {
                return ResourceManager.GetString("HavuzAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Havuz ismi boş geçilemez. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string HavuzAdiBosOlamaz {
            get {
                return ResourceManager.GetString("HavuzAdiBosOlamaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Havuz Ayarları benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string havuzAyarlari {
            get {
                return ResourceManager.GetString("havuzAyarlari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Havuz başarılı bir şekilde düzenlenmiştir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string HavuzDuzenlendi {
            get {
                return ResourceManager.GetString("HavuzDuzenlendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Havuz başarılı bir şekilde eklenmiştir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string HavuzEklendi {
            get {
                return ResourceManager.GetString("HavuzEklendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silinen havuz başarılı bir şekilde geri alınmıştır benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string HavuzGeriAlmaBasarili {
            get {
                return ResourceManager.GetString("HavuzGeriAlmaBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Havuz Sıcaklık Bilgileri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string havuzSicaklikBilgileri {
            get {
                return ResourceManager.GetString("havuzSicaklikBilgileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Havuz başarılı bir şekilde silinmiştir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string HavuzSilmeBasarili {
            get {
                return ResourceManager.GetString("HavuzSilmeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hayır benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Hayır {
            get {
                return ResourceManager.GetString("Hayır", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hoşgeldiniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Hoşgeldiniz {
            get {
                return ResourceManager.GetString("Hoşgeldiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen Çift Kişilik Yatak Bölümüne sadece rakam giriniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ikiKisilikRakamGir {
            get {
                return ResourceManager.GetString("ikiKisilikRakamGir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İki Kişilik Yatak Sayısı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ikiKisilikYatakSayisi {
            get {
                return ResourceManager.GetString("ikiKisilikYatakSayisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İnternet bağlantısı olmadığından dolayı programı kullanamazsınız benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string internetYok {
            get {
                return ResourceManager.GetString("internetYok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kat Ayarları benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string katAyarlari {
            get {
                return ResourceManager.GetString("katAyarlari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kat başarılı bir şekilde düzenlenmiştir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string KatDuzenlemeBasarili {
            get {
                return ResourceManager.GetString("KatDuzenlemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kategori başarılı bir şekilde eklenmiştir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string KategoriEklemeBasarili {
            get {
                return ResourceManager.GetString("KategoriEklemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kategori adı boş olamaz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string KategoriIsmiBosGecilemez {
            get {
                return ResourceManager.GetString("KategoriIsmiBosGecilemez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kat başarılı bir şekilde eklenmiştir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string KatEklemeBasarili {
            get {
                return ResourceManager.GetString("KatEklemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kat başarılı bir şekilde geri alınmıştır benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string katGeriAlmaIslemiBasarili {
            get {
                return ResourceManager.GetString("katGeriAlmaIslemiBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kat başarılı bir şekilde silinmiştir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string KatSilmeBasarili {
            get {
                return ResourceManager.GetString("KatSilmeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen önce katta bulunan odaları siliniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string kattaBulunanOdalariSilin {
            get {
                return ResourceManager.GetString("kattaBulunanOdalariSilin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen önce katta bulunan salonları siliniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string kattaBulunanSalonlariSilin {
            get {
                return ResourceManager.GetString("kattaBulunanSalonlariSilin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kişi Limiti Var benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string KisiLimitiVar {
            get {
                return ResourceManager.GetString("KisiLimitiVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grup benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Kitle {
            get {
                return ResourceManager.GetString("Kitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kriter: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string KriterLabel {
            get {
                return ResourceManager.GetString("KriterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı adı boş geçilemez. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string KullaniciAdiHata {
            get {
                return ResourceManager.GetString("KullaniciAdiHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı şifresi boş geçilemez benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string KullaniciSifreHata {
            get {
                return ResourceManager.GetString("KullaniciSifreHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Açıklama: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblAciklama {
            get {
                return ResourceManager.GetString("lblAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adres: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblAdres {
            get {
                return ResourceManager.GetString("lblAdres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İsim ve Soyisim: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblAdveSoyad {
            get {
                return ResourceManager.GetString("lblAdveSoyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başlık: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblBaslik {
            get {
                return ResourceManager.GetString("lblBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bitiş Zamanı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblBitisZamani {
            get {
                return ResourceManager.GetString("lblBitisZamani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blok Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblBlokAdi {
            get {
                return ResourceManager.GetString("lblBlokAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blok Listesi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblBlokListesi {
            get {
                return ResourceManager.GetString("lblBlokListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bloktaki Katlar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblBloktakiKatlar {
            get {
                return ResourceManager.GetString("lblBloktakiKatlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bölüme Ait Kategoriler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblBolumeAitKateglblBolumeAitKategori {
            get {
                return ResourceManager.GetString("lblBolumeAitKateglblBolumeAitKategori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dil: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblDil {
            get {
                return ResourceManager.GetString("lblDil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duyuru Grubu: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblDuyuruGrubu {
            get {
                return ResourceManager.GetString("lblDuyuruGrubu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Etkinlik İsmi: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblEtkinlikismi {
            get {
                return ResourceManager.GetString("lblEtkinlikismi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Görevli Personeller benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblGorevliPersoneller {
            get {
                return ResourceManager.GetString("lblGorevliPersoneller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Güncelleme Tarihi: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblGuncellemeTarihi {
            get {
                return ResourceManager.GetString("lblGuncellemeTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Havuz Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblHavuzAdi {
            get {
                return ResourceManager.GetString("lblHavuzAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Havuzlar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblHavuzlar {
            get {
                return ResourceManager.GetString("lblHavuzlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İçerik: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lbliCerik {
            get {
                return ResourceManager.GetString("lbliCerik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kat Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblKatAdi {
            get {
                return ResourceManager.GetString("lblKatAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kategori Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblKategoriAdi {
            get {
                return ResourceManager.GetString("lblKategoriAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kategorinin Ait Olduğu Bölüm benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblKategoriAitBolum {
            get {
                return ResourceManager.GetString("lblKategoriAitBolum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Katılacaklar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblKatilacaklar {
            get {
                return ResourceManager.GetString("lblKatilacaklar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Katılım Kriteri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblKatilimKriter {
            get {
                return ResourceManager.GetString("lblKatilimKriter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kişi Limiti: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblKisiLimiti {
            get {
                return ResourceManager.GetString("lblKisiLimiti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı Adı: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblKullaniciAdi {
            get {
                return ResourceManager.GetString("lblKullaniciAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı Departman benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblKullaniciDepartman {
            get {
                return ResourceManager.GetString("lblKullaniciDepartman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı Listesi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblKullanıcıListesi {
            get {
                return ResourceManager.GetString("lblKullanıcıListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mail: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblMail {
            get {
                return ResourceManager.GetString("lblMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İsim: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblMusteriAdi {
            get {
                return ResourceManager.GetString("lblMusteriAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Soyisim: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblMusteriSoyadi {
            get {
                return ResourceManager.GetString("lblMusteriSoyadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Otel Adı: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblOtelAdi {
            get {
                return ResourceManager.GetString("lblOtelAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Personel Grubu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblPersonelGrubu {
            get {
                return ResourceManager.GetString("lblPersonelGrubu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Personel Listesi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblPersonelListesi {
            get {
                return ResourceManager.GetString("lblPersonelListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Personel Yetkisi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblPersonelYetkisi {
            get {
                return ResourceManager.GetString("lblPersonelYetkisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Salon Adı: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblSalonAdi {
            get {
                return ResourceManager.GetString("lblSalonAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Salon Adresi: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblSalonAdresi {
            get {
                return ResourceManager.GetString("lblSalonAdresi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bulunduğu Blok: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblSalonBulunduguBlok {
            get {
                return ResourceManager.GetString("lblSalonBulunduguBlok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bulunduğu Kat: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblSalonBulunduguKat {
            get {
                return ResourceManager.GetString("lblSalonBulunduguKat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Salon Kategorisi: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblSalonKategori {
            get {
                return ResourceManager.GetString("lblSalonKategori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Salon Sorumlusu: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblSalonSorumlusu {
            get {
                return ResourceManager.GetString("lblSalonSorumlusu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şifre: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblSifre {
            get {
                return ResourceManager.GetString("lblSifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sorumlu Olduğu Blok: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblSorumluBlok {
            get {
                return ResourceManager.GetString("lblSorumluBlok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sorumlu Olduğu Kat: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblSorumluKat {
            get {
                return ResourceManager.GetString("lblSorumluKat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tanımlı Yetki benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblTanımlıYetki {
            get {
                return ResourceManager.GetString("lblTanımlıYetki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tarih: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblTarih {
            get {
                return ResourceManager.GetString("lblTarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Telefon: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblTelefon {
            get {
                return ResourceManager.GetString("lblTelefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toplantı Konusu: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblToplantiKonusu {
            get {
                return ResourceManager.GetString("lblToplantiKonusu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toplantı Salonu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblToplantiSalonu {
            get {
                return ResourceManager.GetString("lblToplantiSalonu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toplantı Tarihi: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblToplantiTarihi {
            get {
                return ResourceManager.GetString("lblToplantiTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yetki Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblYetki {
            get {
                return ResourceManager.GetString("lblYetki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yetkiler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblYetkiler {
            get {
                return ResourceManager.GetString("lblYetkiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bu alan sadece yetkili kişiler tarafından değiştirilebilinir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblYetkiliKisiDegistirebilir {
            get {
                return ResourceManager.GetString("lblYetkiliKisiDegistirebilir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Liste Güncelle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ListeGuncelle {
            get {
                return ResourceManager.GetString("ListeGuncelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Giriş Ekranı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string LoginFormText {
            get {
                return ResourceManager.GetString("LoginFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bu müşteri önceden sisteme Google ya da Facebook ile giriş yapmıştır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MusterFaceVarHata {
            get {
                return ResourceManager.GetString("MusterFaceVarHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Müsteri Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MusteriAdi {
            get {
                return ResourceManager.GetString("MusteriAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Müşteri Adı: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MusteriAdLabel {
            get {
                return ResourceManager.GetString("MusteriAdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Müşteri Check-in benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string musteriCheckin {
            get {
                return ResourceManager.GetString("musteriCheckin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başarılı bir şekilde müşteri güncellenmiştir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MusteriGuncellemeBasarili {
            get {
                return ResourceManager.GetString("MusteriGuncellemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Müşteri Listesi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string musteriListesi {
            get {
                return ResourceManager.GetString("musteriListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bu müşteri önceden sisteme kaydedilmiş. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MusteriSistemeKayitliHata {
            get {
                return ResourceManager.GetString("MusteriSistemeKayitliHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Müşteri Soyadı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MusteriSoyadi {
            get {
                return ResourceManager.GetString("MusteriSoyadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Müşteri Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string musteriTanimlama {
            get {
                return ResourceManager.GetString("musteriTanimlama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Müşteri başarı ile tanımlanmıştır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MusteriTanimlamaBasarili {
            get {
                return ResourceManager.GetString("MusteriTanimlamaBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Müşteri Telefon Numarası benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MusteriTelefonNumarasi {
            get {
                return ResourceManager.GetString("MusteriTelefonNumarasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İstenilen kriterlerde herhangi bir {0}kayıt bulunamamıştır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NoResult {
            get {
                return ResourceManager.GetString("NoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen oda bilgilerini kontrol ediniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OdaBilgisiEksik {
            get {
                return ResourceManager.GetString("OdaBilgisiEksik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Odadan Sorumlu Personel benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OdadanSorumluPersonel {
            get {
                return ResourceManager.GetString("OdadanSorumluPersonel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Girilen tarih aralığında bu odada rezervasyon {0}ya da check-in işlemi bulunmaktadır benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string odadaRezervasyonCheckinVar {
            get {
                return ResourceManager.GetString("odadaRezervasyonCheckinVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başarılı bir şekilde oda düzenlenmiştir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OdaDuzenlemeBasarili {
            get {
                return ResourceManager.GetString("OdaDuzenlemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başarılı bir şekilde oda eklenmiştir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OdaEklemeBasarili {
            get {
                return ResourceManager.GetString("OdaEklemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başarılı bir şekilde oda geri alınmıştır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string odaGeriAlmaBasarili {
            get {
                return ResourceManager.GetString("odaGeriAlmaBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oda Grubu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OdaGrubu {
            get {
                return ResourceManager.GetString("OdaGrubu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oda Grubu: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OdaGrupLabel {
            get {
                return ResourceManager.GetString("OdaGrupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oda Kontrol benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string odaKontrol {
            get {
                return ResourceManager.GetString("odaKontrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oda Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OdaNumarasi {
            get {
                return ResourceManager.GetString("OdaNumarasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başarılı bir şekilde oda silinmiştir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string odaSilmeBasarili {
            get {
                return ResourceManager.GetString("odaSilmeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Öğün Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ogunEkle {
            get {
                return ResourceManager.GetString("ogunEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Öğün Tanımlama benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ogunTanimlama {
            get {
                return ResourceManager.GetString("ogunTanimlama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ölçülemedi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Olculemedi {
            get {
                return ResourceManager.GetString("Olculemedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen salon eklemek istediğiniz bloğa önce kat ekleyin veya bir kat seçin benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string onceKatEkleyiniz {
            get {
                return ResourceManager.GetString("onceKatEkleyiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başarılı bir şekilde otel bilgileri sisteme eklenmiştir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string otelBilgileriEklemeBasarili {
            get {
                return ResourceManager.GetString("otelBilgileriEklemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Müşteri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OzelMusteri {
            get {
                return ResourceManager.GetString("OzelMusteri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Özel Yemek Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ozelYemekEkle {
            get {
                return ResourceManager.GetString("ozelYemekEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Personel benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Personel {
            get {
                return ResourceManager.GetString("Personel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Personel Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string personelAdi {
            get {
                return ResourceManager.GetString("personelAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Personel daha önceden tanımlanmış benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string personelDahaOncedenTanimlanmis {
            get {
                return ResourceManager.GetString("personelDahaOncedenTanimlanmis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Personel Departmanı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string personelDepartman {
            get {
                return ResourceManager.GetString("personelDepartman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başarılı bir şekilde personel eklenmiştir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string personelEklemeBasarili {
            get {
                return ResourceManager.GetString("personelEklemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başarılı bir şekilde silinen personel geri alındı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PersonelGeriAlindi {
            get {
                return ResourceManager.GetString("PersonelGeriAlindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Personel Görevlendir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string personelGorevlendir {
            get {
                return ResourceManager.GetString("personelGorevlendir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başarılı bir şekilde personel güncellenmiştir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string personelGuncellemeBasarili {
            get {
                return ResourceManager.GetString("personelGuncellemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Personel Kontrol benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string personelKontrol {
            get {
                return ResourceManager.GetString("personelKontrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Personel Seç benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string personelSecimi {
            get {
                return ResourceManager.GetString("personelSecimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bu personel sistemden silinmiş. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string personelSilinmis {
            get {
                return ResourceManager.GetString("personelSilinmis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Personel silme işleminiz başarılı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string personelSilmeBasarili {
            get {
                return ResourceManager.GetString("personelSilmeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Personel Soyadı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string personelSoyadi {
            get {
                return ResourceManager.GetString("personelSoyadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Programa giriş yapan kullanıcı : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string programaGirisYapanKullanici {
            get {
                return ResourceManager.GetString("programaGirisYapanKullanici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bu program zaten çalışıyor benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProgramCalisiyorHata {
            get {
                return ResourceManager.GetString("ProgramCalisiyorHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Programdan çıkış için emin misiniz? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProgramCikisOnay {
            get {
                return ResourceManager.GetString("ProgramCikisOnay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rezervasyon işlemi başarı ile sonuçlanmıştır benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string RezervasyonBasarili {
            get {
                return ResourceManager.GetString("RezervasyonBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rezervasyon işlemi başarılı bir şekilde iptal edilmiştir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string RezervasyonIptal {
            get {
                return ResourceManager.GetString("RezervasyonIptal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rezervasyon İptal Et benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string RezervasyoniptalEt {
            get {
                return ResourceManager.GetString("RezervasyoniptalEt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reserved Rooms benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string RezerveEdilmisOdalar {
            get {
                return ResourceManager.GetString("RezerveEdilmisOdalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Önceden rezerve edilmiş oda bulunmamaktadır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string rezerveOdalarBos {
            get {
                return ResourceManager.GetString("rezerveOdalarBos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Saat {
            get {
                return ResourceManager.GetString("Saat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Salon başarılı bir şekilde eklenmiştir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SalonEklemeBasarili {
            get {
                return ResourceManager.GetString("SalonEklemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Salon ismi boş olamaz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string salonIsmiBosGecilemez {
            get {
                return ResourceManager.GetString("salonIsmiBosGecilemez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen salon sorumlusu seçiniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string salonSorumlusuSeciniz {
            get {
                return ResourceManager.GetString("salonSorumlusuSeciniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sıcaklık benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Sicaklik {
            get {
                return ResourceManager.GetString("Sicaklik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Sil {
            get {
                return ResourceManager.GetString("Sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen silinecek bloğu seçiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SilinecekBlokSec {
            get {
                return ResourceManager.GetString("SilinecekBlokSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen önce silinecek etkinliği seçiniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string silinecekEtkinlikSecin {
            get {
                return ResourceManager.GetString("silinecekEtkinlikSecin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen silinecek havuzu seçiniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SilinecekHavuzSeciniz {
            get {
                return ResourceManager.GetString("SilinecekHavuzSeciniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen önce silinecek katı seçiniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SilinecekKatSec {
            get {
                return ResourceManager.GetString("SilinecekKatSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen önce silinecek personeli seçiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string silinecekPersonelSec {
            get {
                return ResourceManager.GetString("silinecekPersonelSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silinen Etkinliği Geri Al benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SilinenEtkinligiGeriAl {
            get {
                return ResourceManager.GetString("SilinenEtkinligiGeriAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silinen Etkinlikleri Göster benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SilinenEtkinlikleriGoster {
            get {
                return ResourceManager.GetString("SilinenEtkinlikleriGoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silinen havuz başarılı bir şekilde geri alınmıştır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SilinenHavuzGeriAlindi {
            get {
                return ResourceManager.GetString("SilinenHavuzGeriAlindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silinmiş Duyuruları Geri Al benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string silinmisDuyurulariGeriAl {
            get {
                return ResourceManager.GetString("silinmisDuyurulariGeriAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silinmiş Duyuruları Göster benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string silinmisDuyurulariGoster {
            get {
                return ResourceManager.GetString("silinmisDuyurulariGoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silinmiş Duyuruları Gösterme benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SilinmisDuyurulariGosterme {
            get {
                return ResourceManager.GetString("SilinmisDuyurulariGosterme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silinmiş Kayıtları Geri Al benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SilinmisKayitlariGeriAl {
            get {
                return ResourceManager.GetString("SilinmisKayitlariGeriAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silinmiş Kayıtları Göster benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SilinmisKayitlariGoster {
            get {
                return ResourceManager.GetString("SilinmisKayitlariGoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silinmiş Kayıtları Gösterme benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SilinmisKayitlariGosterme {
            get {
                return ResourceManager.GetString("SilinmisKayitlariGosterme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silinmiş odaları göster benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string silinmisOdalariGoster {
            get {
                return ResourceManager.GetString("silinmisOdalariGoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silinmiş Odaları Gösterme benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string silinmisOdalariGosterme {
            get {
                return ResourceManager.GetString("silinmisOdalariGosterme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silinmiş Odayı Geri Al benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string silinmisOdayiGeriAl {
            get {
                return ResourceManager.GetString("silinmisOdayiGeriAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silinmiş Personeli Geri Al benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string silinmisPersoneliGeriAl {
            get {
                return ResourceManager.GetString("silinmisPersoneliGeriAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silinmiş Personelleri Göster benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string silinmisPersonelleriGoster {
            get {
                return ResourceManager.GetString("silinmisPersonelleriGoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen silinecek duyuruyu seçiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SilmekicinDuyuruSec {
            get {
                return ResourceManager.GetString("SilmekicinDuyuruSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silmek için lütfen bir oda seçiniz ve ardından sil tuşuna basınız. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string silmekIcınOdaSec {
            get {
                return ResourceManager.GetString("silmekIcınOdaSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Son Gün benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string sonGun {
            get {
                return ResourceManager.GetString("sonGun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tamam benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Tamam {
            get {
                return ResourceManager.GetString("Tamam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen girdiğiniz tarih bilgilerini kontrol ediniz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TarihKontrol {
            get {
                return ResourceManager.GetString("TarihKontrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen Tek Kişilik Yatak Bölümüne sadece rakam giriniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tekKisilikRakamGir {
            get {
                return ResourceManager.GetString("tekKisilikRakamGir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tek Kişilik Yatak Sayısı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tekKisilikYatakSayisi {
            get {
                return ResourceManager.GetString("tekKisilikYatakSayisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temizlenme Tarihi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string temizlenmeTarihi {
            get {
                return ResourceManager.GetString("temizlenmeTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başarılı bir şekilde oda temizlenmiştir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string temizlikBasarili {
            get {
                return ResourceManager.GetString("temizlikBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temizlik Yap benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string temizlikYap {
            get {
                return ResourceManager.GetString("temizlikYap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ayarlar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tileAyarlar {
            get {
                return ResourceManager.GetString("tileAyarlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bilgilendirme Formu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tileBilgilendirmeFormu {
            get {
                return ResourceManager.GetString("tileBilgilendirmeFormu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blok Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tileBlokEkle {
            get {
                return ResourceManager.GetString("tileBlokEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duyuru İşlemleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tileDuyuru {
            get {
                return ResourceManager.GetString("tileDuyuru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Etkinlik İşlemleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tileEtkinlik {
            get {
                return ResourceManager.GetString("tileEtkinlik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oto Gece Modu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tileGeceModu {
            get {
                return ResourceManager.GetString("tileGeceModu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Havuz Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tileHavuzEkle {
            get {
                return ResourceManager.GetString("tileHavuzEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Müşteri Tanımlama benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tileItemMusteriTanimlama {
            get {
                return ResourceManager.GetString("tileItemMusteriTanimlama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kategori Tanımlamaları benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tileKategoriTanimlamalari {
            get {
                return ResourceManager.GetString("tileKategoriTanimlamalari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kat Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tileKatEkle {
            get {
                return ResourceManager.GetString("tileKatEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı Tercihleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tileKullaniciTercihleri {
            get {
                return ResourceManager.GetString("tileKullaniciTercihleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lisans İşlemleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tileLisans {
            get {
                return ResourceManager.GetString("tileLisans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Müşteri İşlemleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tileMusteri {
            get {
                return ResourceManager.GetString("tileMusteri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oda İşlemleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tileOda {
            get {
                return ResourceManager.GetString("tileOda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oda Check-in benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tileOdaCheckin {
            get {
                return ResourceManager.GetString("tileOdaCheckin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oda Listesi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tileOdaListesi {
            get {
                return ResourceManager.GetString("tileOdaListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oda Rezerve Et benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tileOdaRezerveEt {
            get {
                return ResourceManager.GetString("tileOdaRezerveEt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oda Tanımlama benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tileOdaTanimlama {
            get {
                return ResourceManager.GetString("tileOdaTanimlama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Onay Formu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tileOnayForm {
            get {
                return ResourceManager.GetString("tileOnayForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Otel Tanımlamaları benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tileOtelTanimlamalari {
            get {
                return ResourceManager.GetString("tileOtelTanimlamalari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Personel İşlemleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tilePersonel {
            get {
                return ResourceManager.GetString("tilePersonel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Personel Listesi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tilePersonelListesi {
            get {
                return ResourceManager.GetString("tilePersonelListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Personel Oluştur benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tilePersonelOlustur {
            get {
                return ResourceManager.GetString("tilePersonelOlustur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Renk Değiştir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tileRenkDegistir {
            get {
                return ResourceManager.GetString("tileRenkDegistir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Salon Tanımlamaları benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tileSalonTanimlamalari {
            get {
                return ResourceManager.GetString("tileSalonTanimlamalari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sıcaklık Bilgileri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tileSicaklik {
            get {
                return ResourceManager.GetString("tileSicaklik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Süre Uzat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tileSureUzat {
            get {
                return ResourceManager.GetString("tileSureUzat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temizlik İşlemleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tileTemizlik {
            get {
                return ResourceManager.GetString("tileTemizlik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toplantı İşlemleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tileToplanti {
            get {
                return ResourceManager.GetString("tileToplanti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toplantı Listesi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tileToplantiListesi {
            get {
                return ResourceManager.GetString("tileToplantiListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toplantı Oluştur benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tileToplantiOlustur {
            get {
                return ResourceManager.GetString("tileToplantiOlustur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yemek İşlemleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tileYemek {
            get {
                return ResourceManager.GetString("tileYemek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yemek Listesi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tileYemekListesi {
            get {
                return ResourceManager.GetString("tileYemekListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yetki İşlemleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tileYetki {
            get {
                return ResourceManager.GetString("tileYetki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başarılı bir şekilde toplantı eklenmiştir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ToplantiEklemeBasarili {
            get {
                return ResourceManager.GetString("ToplantiEklemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tüm Bilgileri Göster benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tumBilgileriGoster {
            get {
                return ResourceManager.GetString("tumBilgileriGoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tümü benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Tümü {
            get {
                return ResourceManager.GetString("Tümü", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uyarı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string uyari {
            get {
                return ResourceManager.GetString("uyari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yardım benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Yardim {
            get {
                return ResourceManager.GetString("Yardim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yemek Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string yemekAdi {
            get {
                return ResourceManager.GetString("yemekAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yemek adı boş olamaz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string yemekAdiBosGecilemez {
            get {
                return ResourceManager.GetString("yemekAdiBosGecilemez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başarılı bir şekilde yemek eklenmiştir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string yemekEklemeBasarili {
            get {
                return ResourceManager.GetString("yemekEklemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yemek Salonu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string yemekSalonu {
            get {
                return ResourceManager.GetString("yemekSalonu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başarılı bir şekilde yemek silinmiştir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string yemekSilmeBasarili {
            get {
                return ResourceManager.GetString("yemekSilmeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yemek Türü benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string yemekTuru {
            get {
                return ResourceManager.GetString("yemekTuru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yetki Ayarları benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string yetkiAyarlari {
            get {
                return ResourceManager.GetString("yetkiAyarlari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başarılı bir şekilde personel yetkisi güncellenmiştir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string YetkiGuncellemeBasarili {
            get {
                return ResourceManager.GetString("YetkiGuncellemeBasarili", resourceCulture);
            }
        }
    }
}
