//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otel_Uygulamasi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Otel_Uygulamasi.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama boş olamaz.
        /// </summary>
        internal static string aciklamaBosGecilemez {
            get {
                return ResourceManager.GetString("aciklamaBosGecilemez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ardunio Bağlı Değil.
        /// </summary>
        internal static string ArdunioBagliDegil {
            get {
                return ResourceManager.GetString("ArdunioBagliDegil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ardunio Sıcaklık Bağlantı.
        /// </summary>
        internal static string ArdunioSicaklinBaglanti {
            get {
                return ResourceManager.GetString("ArdunioSicaklinBaglanti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı bir şekilde check-in yapılmıştır.
        /// </summary>
        internal static string BasariliCheckin {
            get {
                return ResourceManager.GetString("BasariliCheckin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlangıç Zamanı.
        /// </summary>
        internal static string baslangicZamani {
            get {
                return ResourceManager.GetString("baslangicZamani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blok başarılı bir şekilde düzenlenmiştir..
        /// </summary>
        internal static string BlokDuzenlendi {
            get {
                return ResourceManager.GetString("BlokDuzenlendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blok başarılı bir şekilde eklenmiştir..
        /// </summary>
        internal static string Blokeklendi {
            get {
                return ResourceManager.GetString("Blokeklendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bir blok seçiniz.
        /// </summary>
        internal static string blokIsmiBosGecilmez {
            get {
                return ResourceManager.GetString("blokIsmiBosGecilmez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blok ismi boş geçilemez..
        /// </summary>
        internal static string BlokismiBosOlamaz {
            get {
                return ResourceManager.GetString("BlokismiBosOlamaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blok başarılı bir şekilde silinmiştir..
        /// </summary>
        internal static string BlokSilmeBasarili {
            get {
                return ResourceManager.GetString("BlokSilmeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boş Odalar.
        /// </summary>
        internal static string BosOdalar {
            get {
                return ResourceManager.GetString("BosOdalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destek.
        /// </summary>
        internal static string btnDestek {
            get {
                return ResourceManager.GetString("btnDestek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        internal static string btnEkle {
            get {
                return ResourceManager.GetString("btnEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrele.
        /// </summary>
        internal static string btnFiltrele {
            get {
                return ResourceManager.GetString("btnFiltrele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        internal static string btnGiris {
            get {
                return ResourceManager.GetString("btnGiris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        internal static string btnGonder {
            get {
                return ResourceManager.GetString("btnGonder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görevlendir.
        /// </summary>
        internal static string btnGorevlendir {
            get {
                return ResourceManager.GetString("btnGorevlendir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görevlendirme.
        /// </summary>
        internal static string btnGorevlendirme {
            get {
                return ResourceManager.GetString("btnGorevlendirme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gözat.
        /// </summary>
        internal static string btnGozat {
            get {
                return ResourceManager.GetString("btnGozat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal.
        /// </summary>
        internal static string btnIptal {
            get {
                return ResourceManager.GetString("btnIptal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapat.
        /// </summary>
        internal static string btnKapat {
            get {
                return ResourceManager.GetString("btnKapat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kat Ekle.
        /// </summary>
        internal static string btnKatEkle {
            get {
                return ResourceManager.GetString("btnKatEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        internal static string btnKaydet {
            get {
                return ResourceManager.GetString("btnKaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klavye aç.
        /// </summary>
        internal static string btnKlavyeAc {
            get {
                return ResourceManager.GetString("btnKlavyeAc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onayla.
        /// </summary>
        internal static string btnOnayla {
            get {
                return ResourceManager.GetString("btnOnayla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçenekler.
        /// </summary>
        internal static string btnSecenekler {
            get {
                return ResourceManager.GetString("btnSecenekler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temizle.
        /// </summary>
        internal static string btnTemizle {
            get {
                return ResourceManager.GetString("btnTemizle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Personeller.
        /// </summary>
        internal static string chechBoxTümPersoneller {
            get {
                return ResourceManager.GetString("chechBoxTümPersoneller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özel Gönderim.
        /// </summary>
        internal static string CheckBoxOzelGonderim {
            get {
                return ResourceManager.GetString("CheckBoxOzelGonderim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-in Yap.
        /// </summary>
        internal static string checkinYap {
            get {
                return ResourceManager.GetString("checkinYap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-out işlemi başarı ile tamamlanmıştır..
        /// </summary>
        internal static string CheckoutBasarili {
            get {
                return ResourceManager.GetString("CheckoutBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-out işlemi için önce bir kayıt seçiniz.
        /// </summary>
        internal static string checkoutKayitSec {
            get {
                return ResourceManager.GetString("checkoutKayitSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı ve şifremi hatırla.
        /// </summary>
        internal static string chHatirla {
            get {
                return ResourceManager.GetString("chHatirla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çift Kişilik Yatak Sayısı.
        /// </summary>
        internal static string CiftKisilikYatakSayisi {
            get {
                return ResourceManager.GetString("CiftKisilikYatakSayisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış Tarihi.
        /// </summary>
        internal static string CikisTarihi {
            get {
                return ResourceManager.GetString("CikisTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış tarihi uzatıldı.
        /// </summary>
        internal static string cikisTarihiUzatıldı {
            get {
                return ResourceManager.GetString("cikisTarihiUzatıldı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyuru Ekle.
        /// </summary>
        internal static string duyuruEkle {
            get {
                return ResourceManager.GetString("duyuruEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyuru başarılı bir şekilde eklenmiştir..
        /// </summary>
        internal static string DuyuruEklemeBasarili {
            get {
                return ResourceManager.GetString("DuyuruEklemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı bir şekilde duyuru geri alınmıştır..
        /// </summary>
        internal static string DuyuruGerialmaBasarili {
            get {
                return ResourceManager.GetString("DuyuruGerialmaBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyuru başarılı bir şekilde güncellenmiştir..
        /// </summary>
        internal static string DuyuruGuncellemeBasarili {
            get {
                return ResourceManager.GetString("DuyuruGuncellemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyuru Listesi.
        /// </summary>
        internal static string duyuruListesi {
            get {
                return ResourceManager.GetString("duyuruListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı bir şekilde duyuru silinmiştir..
        /// </summary>
        internal static string DuyuruSilmeBasarili {
            get {
                return ResourceManager.GetString("DuyuruSilmeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenle.
        /// </summary>
        internal static string Duzenle {
            get {
                return ResourceManager.GetString("Duzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenlemek için blok seçmelisiniz..
        /// </summary>
        internal static string DuzenlemekIcınBlokSec {
            get {
                return ResourceManager.GetString("DuzenlemekIcınBlokSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen önce düzenlemek {0}istediğiniz duyuruyu seçiniz.
        /// </summary>
        internal static string DuzenlemekicinDuyuruSec {
            get {
                return ResourceManager.GetString("DuzenlemekicinDuyuruSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenlemek için lütfen bir oda seçiniz ve ardından düzenle tuşuna basınız..
        /// </summary>
        internal static string duzenlemekIcınOdaSec {
            get {
                return ResourceManager.GetString("duzenlemekIcınOdaSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen önce düzenlenecek etkinliği seçiniz.
        /// </summary>
        internal static string duzenlenecekEtkinlikSecin {
            get {
                return ResourceManager.GetString("duzenlenecekEtkinlikSecin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenlenecek havuzu seçiniz.
        /// </summary>
        internal static string DuzenlenecekHavuzSec {
            get {
                return ResourceManager.GetString("DuzenlenecekHavuzSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen önce düzenlenecek katı seçiniz.
        /// </summary>
        internal static string DuzenlenecekKatSec {
            get {
                return ResourceManager.GetString("DuzenlenecekKatSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen önce düzenlenecek personeli seçiniz..
        /// </summary>
        internal static string duzenlenecekPersonelSec {
            get {
                return ResourceManager.GetString("duzenlenecekPersonelSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eklenecek gün sayısı pozitif olmalıdır.
        /// </summary>
        internal static string eklenecekGunSayisiPozitifHata {
            get {
                return ResourceManager.GetString("eklenecekGunSayisiPozitifHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen check-in bilgilerini kontrol ediniz.
        /// </summary>
        internal static string EksikCheckinBilgisi {
            get {
                return ResourceManager.GetString("EksikCheckinBilgisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik bilgilerini eksiksiz bir şekilde girdiğinizden emin olunuz..
        /// </summary>
        internal static string EksikEtkinlikBilgileri {
            get {
                return ResourceManager.GetString("EksikEtkinlikBilgileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervasyon bilgilerinizi lütfen kontrol ediniz.
        /// </summary>
        internal static string EksikRezervasyonBilgisi {
            get {
                return ResourceManager.GetString("EksikRezervasyonBilgisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen geçerli bir e-mail adresi giriniz.
        /// </summary>
        internal static string eMailHata {
            get {
                return ResourceManager.GetString("eMailHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Ekle.
        /// </summary>
        internal static string etkinlikEkle {
            get {
                return ResourceManager.GetString("etkinlikEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı bir şekilde etkinlik eklenmiştir..
        /// </summary>
        internal static string EtkinlikEklemeBasarili {
            get {
                return ResourceManager.GetString("EtkinlikEklemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik başarılı bir şekilde geri alınmıştır.
        /// </summary>
        internal static string etkinlikGeriAlmaBasarili {
            get {
                return ResourceManager.GetString("etkinlikGeriAlmaBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı bir şekilde etkinlik güncellenmiştir.
        /// </summary>
        internal static string EtkinlikGuncellemeBasarili {
            get {
                return ResourceManager.GetString("EtkinlikGuncellemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik Listesi.
        /// </summary>
        internal static string etkinlikListesi {
            get {
                return ResourceManager.GetString("etkinlikListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik başarılı bir şekilde silinmiştir.
        /// </summary>
        internal static string etkinlikSilinmistir {
            get {
                return ResourceManager.GetString("etkinlikSilinmistir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evet.
        /// </summary>
        internal static string Evet {
            get {
                return ResourceManager.GetString("Evet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen geri alınacak duyuruyu seçiniz..
        /// </summary>
        internal static string GeriAlinacakDuyuruSec {
            get {
                return ResourceManager.GetString("GeriAlinacakDuyuruSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri Alınacak Etkinlik Seçiniz.
        /// </summary>
        internal static string GeriAlinacakEtkinlikSec {
            get {
                return ResourceManager.GetString("GeriAlinacakEtkinlikSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen önce geri almak istediğiniz etkinliği seçiniz.
        /// </summary>
        internal static string geriAlinacakEtkinlikSeciniz {
            get {
                return ResourceManager.GetString("geriAlinacakEtkinlikSeciniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen geri almak istediğiniz katı seçiniz.
        /// </summary>
        internal static string geriAlinacakKatiSecin {
            get {
                return ResourceManager.GetString("geriAlinacakKatiSecin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen önce geri alınacak odayı seçin.
        /// </summary>
        internal static string geriAlinacakOdayiSecin {
            get {
                return ResourceManager.GetString("geriAlinacakOdayiSecin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Tarihi.
        /// </summary>
        internal static string GirisTarihi {
            get {
                return ResourceManager.GetString("GirisTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncellenemedi.
        /// </summary>
        internal static string Guncellenemedi {
            get {
                return ResourceManager.GetString("Guncellenemedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gün Ekle.
        /// </summary>
        internal static string gunEkle {
            get {
                return ResourceManager.GetString("gunEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eklenecek Gün Sayısı.
        /// </summary>
        internal static string GunSayisi {
            get {
                return ResourceManager.GetString("GunSayisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı ya da şifre hatalıdır.
        /// </summary>
        internal static string HataliKullaniciAdiSifre {
            get {
                return ResourceManager.GetString("HataliKullaniciAdiSifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Havuz Adı.
        /// </summary>
        internal static string HavuzAdi {
            get {
                return ResourceManager.GetString("HavuzAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Havuz ismi boş geçilemez..
        /// </summary>
        internal static string HavuzAdiBosOlamaz {
            get {
                return ResourceManager.GetString("HavuzAdiBosOlamaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Havuz başarılı bir şekilde düzenlenmiştir..
        /// </summary>
        internal static string HavuzDuzenlendi {
            get {
                return ResourceManager.GetString("HavuzDuzenlendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Havuz başarılı bir şekilde eklenmiştir..
        /// </summary>
        internal static string HavuzEklendi {
            get {
                return ResourceManager.GetString("HavuzEklendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silinen havuz başarılı bir şekilde geri alınmıştır.
        /// </summary>
        internal static string HavuzGeriAlmaBasarili {
            get {
                return ResourceManager.GetString("HavuzGeriAlmaBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Havuz başarılı bir şekilde silinmiştir.
        /// </summary>
        internal static string HavuzSilmeBasarili {
            get {
                return ResourceManager.GetString("HavuzSilmeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hayır.
        /// </summary>
        internal static string Hayır {
            get {
                return ResourceManager.GetString("Hayır", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoşgeldiniz.
        /// </summary>
        internal static string Hoşgeldiniz {
            get {
                return ResourceManager.GetString("Hoşgeldiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Çift Kişilik Yatak Bölümüne sadece rakam giriniz..
        /// </summary>
        internal static string ikiKisilikRakamGir {
            get {
                return ResourceManager.GetString("ikiKisilikRakamGir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İki Kişilik Yatak Sayısı.
        /// </summary>
        internal static string ikiKisilikYatakSayisi {
            get {
                return ResourceManager.GetString("ikiKisilikYatakSayisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İnternet bağlantısı olmadığından dolayı programı kullanamazsınız.
        /// </summary>
        internal static string internetYok {
            get {
                return ResourceManager.GetString("internetYok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kat başarılı bir şekilde düzenlenmiştir.
        /// </summary>
        internal static string KatDuzenlemeBasarili {
            get {
                return ResourceManager.GetString("KatDuzenlemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori başarılı bir şekilde eklenmiştir.
        /// </summary>
        internal static string KategoriEklemeBasarili {
            get {
                return ResourceManager.GetString("KategoriEklemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori adı boş olamaz.
        /// </summary>
        internal static string KategoriIsmiBosGecilemez {
            get {
                return ResourceManager.GetString("KategoriIsmiBosGecilemez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kat başarılı bir şekilde eklenmiştir.
        /// </summary>
        internal static string KatEklemeBasarili {
            get {
                return ResourceManager.GetString("KatEklemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kat başarılı bir şekilde geri alınmıştır.
        /// </summary>
        internal static string katGeriAlmaIslemiBasarili {
            get {
                return ResourceManager.GetString("katGeriAlmaIslemiBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kat başarılı bir şekilde silinmiştir.
        /// </summary>
        internal static string KatSilmeBasarili {
            get {
                return ResourceManager.GetString("KatSilmeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kişi Limiti Var.
        /// </summary>
        internal static string KisiLimitiVar {
            get {
                return ResourceManager.GetString("KisiLimitiVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grup.
        /// </summary>
        internal static string Kitle {
            get {
                return ResourceManager.GetString("Kitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kriter:.
        /// </summary>
        internal static string KriterLabel {
            get {
                return ResourceManager.GetString("KriterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı boş geçilemez..
        /// </summary>
        internal static string KullaniciAdiHata {
            get {
                return ResourceManager.GetString("KullaniciAdiHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı şifresi boş geçilemez.
        /// </summary>
        internal static string KullaniciSifreHata {
            get {
                return ResourceManager.GetString("KullaniciSifreHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama:.
        /// </summary>
        internal static string lblAciklama {
            get {
                return ResourceManager.GetString("lblAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres:.
        /// </summary>
        internal static string lblAdres {
            get {
                return ResourceManager.GetString("lblAdres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim ve Soyisim:.
        /// </summary>
        internal static string lblAdveSoyad {
            get {
                return ResourceManager.GetString("lblAdveSoyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlık:.
        /// </summary>
        internal static string lblBaslik {
            get {
                return ResourceManager.GetString("lblBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitiş Zamanı.
        /// </summary>
        internal static string lblBitisZamani {
            get {
                return ResourceManager.GetString("lblBitisZamani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blok Adı.
        /// </summary>
        internal static string lblBlokAdi {
            get {
                return ResourceManager.GetString("lblBlokAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blok Listesi.
        /// </summary>
        internal static string lblBlokListesi {
            get {
                return ResourceManager.GetString("lblBlokListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloktaki Katlar.
        /// </summary>
        internal static string lblBloktakiKatlar {
            get {
                return ResourceManager.GetString("lblBloktakiKatlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölüme Ait Kategoriler.
        /// </summary>
        internal static string lblBolumeAitKateglblBolumeAitKategori {
            get {
                return ResourceManager.GetString("lblBolumeAitKateglblBolumeAitKategori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil:.
        /// </summary>
        internal static string lblDil {
            get {
                return ResourceManager.GetString("lblDil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyuru Grubu:.
        /// </summary>
        internal static string lblDuyuruGrubu {
            get {
                return ResourceManager.GetString("lblDuyuruGrubu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik İsmi:.
        /// </summary>
        internal static string lblEtkinlikismi {
            get {
                return ResourceManager.GetString("lblEtkinlikismi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görevli Personeller.
        /// </summary>
        internal static string lblGorevliPersoneller {
            get {
                return ResourceManager.GetString("lblGorevliPersoneller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelleme Tarihi:.
        /// </summary>
        internal static string lblGuncellemeTarihi {
            get {
                return ResourceManager.GetString("lblGuncellemeTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Havuz Adı.
        /// </summary>
        internal static string lblHavuzAdi {
            get {
                return ResourceManager.GetString("lblHavuzAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Havuzlar.
        /// </summary>
        internal static string lblHavuzlar {
            get {
                return ResourceManager.GetString("lblHavuzlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçerik:.
        /// </summary>
        internal static string lbliCerik {
            get {
                return ResourceManager.GetString("lbliCerik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kat Adı.
        /// </summary>
        internal static string lblKatAdi {
            get {
                return ResourceManager.GetString("lblKatAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Adı.
        /// </summary>
        internal static string lblKategoriAdi {
            get {
                return ResourceManager.GetString("lblKategoriAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorinin Ait Olduğu Bölüm.
        /// </summary>
        internal static string lblKategoriAitBolum {
            get {
                return ResourceManager.GetString("lblKategoriAitBolum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katılacaklar.
        /// </summary>
        internal static string lblKatilacaklar {
            get {
                return ResourceManager.GetString("lblKatilacaklar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katılım Kriteri.
        /// </summary>
        internal static string lblKatilimKriter {
            get {
                return ResourceManager.GetString("lblKatilimKriter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kişi Limiti:.
        /// </summary>
        internal static string lblKisiLimiti {
            get {
                return ResourceManager.GetString("lblKisiLimiti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı:.
        /// </summary>
        internal static string lblKullaniciAdi {
            get {
                return ResourceManager.GetString("lblKullaniciAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Departman.
        /// </summary>
        internal static string lblKullaniciDepartman {
            get {
                return ResourceManager.GetString("lblKullaniciDepartman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Listesi.
        /// </summary>
        internal static string lblKullanıcıListesi {
            get {
                return ResourceManager.GetString("lblKullanıcıListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail:.
        /// </summary>
        internal static string lblMail {
            get {
                return ResourceManager.GetString("lblMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim:.
        /// </summary>
        internal static string lblMusteriAdi {
            get {
                return ResourceManager.GetString("lblMusteriAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyisim:.
        /// </summary>
        internal static string lblMusteriSoyadi {
            get {
                return ResourceManager.GetString("lblMusteriSoyadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otel Adı:.
        /// </summary>
        internal static string lblOtelAdi {
            get {
                return ResourceManager.GetString("lblOtelAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Grubu.
        /// </summary>
        internal static string lblPersonelGrubu {
            get {
                return ResourceManager.GetString("lblPersonelGrubu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Listesi.
        /// </summary>
        internal static string lblPersonelListesi {
            get {
                return ResourceManager.GetString("lblPersonelListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Yetkisi.
        /// </summary>
        internal static string lblPersonelYetkisi {
            get {
                return ResourceManager.GetString("lblPersonelYetkisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salon Adı:.
        /// </summary>
        internal static string lblSalonAdi {
            get {
                return ResourceManager.GetString("lblSalonAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salon Adresi:.
        /// </summary>
        internal static string lblSalonAdresi {
            get {
                return ResourceManager.GetString("lblSalonAdresi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulunduğu Blok:.
        /// </summary>
        internal static string lblSalonBulunduguBlok {
            get {
                return ResourceManager.GetString("lblSalonBulunduguBlok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulunduğu Kat:.
        /// </summary>
        internal static string lblSalonBulunduguKat {
            get {
                return ResourceManager.GetString("lblSalonBulunduguKat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salon Kategorisi:.
        /// </summary>
        internal static string lblSalonKategori {
            get {
                return ResourceManager.GetString("lblSalonKategori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salon Sorumlusu:.
        /// </summary>
        internal static string lblSalonSorumlusu {
            get {
                return ResourceManager.GetString("lblSalonSorumlusu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre:.
        /// </summary>
        internal static string lblSifre {
            get {
                return ResourceManager.GetString("lblSifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorumlu Olduğu Blok:.
        /// </summary>
        internal static string lblSorumluBlok {
            get {
                return ResourceManager.GetString("lblSorumluBlok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorumlu Olduğu Kat:.
        /// </summary>
        internal static string lblSorumluKat {
            get {
                return ResourceManager.GetString("lblSorumluKat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanımlı Yetki.
        /// </summary>
        internal static string lblTanımlıYetki {
            get {
                return ResourceManager.GetString("lblTanımlıYetki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih:.
        /// </summary>
        internal static string lblTarih {
            get {
                return ResourceManager.GetString("lblTarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon:.
        /// </summary>
        internal static string lblTelefon {
            get {
                return ResourceManager.GetString("lblTelefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplantı Konusu:.
        /// </summary>
        internal static string lblToplantiKonusu {
            get {
                return ResourceManager.GetString("lblToplantiKonusu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplantı Salonu.
        /// </summary>
        internal static string lblToplantiSalonu {
            get {
                return ResourceManager.GetString("lblToplantiSalonu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplantı Tarihi:.
        /// </summary>
        internal static string lblToplantiTarihi {
            get {
                return ResourceManager.GetString("lblToplantiTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetki Adı.
        /// </summary>
        internal static string lblYetki {
            get {
                return ResourceManager.GetString("lblYetki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkiler.
        /// </summary>
        internal static string lblYetkiler {
            get {
                return ResourceManager.GetString("lblYetkiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu alan sadece yetkili kişiler tarafından değiştirilebilinir..
        /// </summary>
        internal static string lblYetkiliKisiDegistirebilir {
            get {
                return ResourceManager.GetString("lblYetkiliKisiDegistirebilir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste Güncelle.
        /// </summary>
        internal static string ListeGuncelle {
            get {
                return ResourceManager.GetString("ListeGuncelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Ekranı.
        /// </summary>
        internal static string LoginFormText {
            get {
                return ResourceManager.GetString("LoginFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu müşteri önceden sisteme Google ya da Facebook ile giriş yapmıştır..
        /// </summary>
        internal static string MusterFaceVarHata {
            get {
                return ResourceManager.GetString("MusterFaceVarHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müsteri Adı.
        /// </summary>
        internal static string MusteriAdi {
            get {
                return ResourceManager.GetString("MusteriAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Adı:.
        /// </summary>
        internal static string MusteriAdLabel {
            get {
                return ResourceManager.GetString("MusteriAdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Check-in.
        /// </summary>
        internal static string musteriCheckin {
            get {
                return ResourceManager.GetString("musteriCheckin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı bir şekilde müşteri güncellenmiştir..
        /// </summary>
        internal static string MusteriGuncellemeBasarili {
            get {
                return ResourceManager.GetString("MusteriGuncellemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Listesi.
        /// </summary>
        internal static string musteriListesi {
            get {
                return ResourceManager.GetString("musteriListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu müşteri önceden sisteme kaydedilmiş..
        /// </summary>
        internal static string MusteriSistemeKayitliHata {
            get {
                return ResourceManager.GetString("MusteriSistemeKayitliHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Soyadı.
        /// </summary>
        internal static string MusteriSoyadi {
            get {
                return ResourceManager.GetString("MusteriSoyadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Ekle.
        /// </summary>
        internal static string musteriTanimlama {
            get {
                return ResourceManager.GetString("musteriTanimlama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri başarı ile tanımlanmıştır..
        /// </summary>
        internal static string MusteriTanimlamaBasarili {
            get {
                return ResourceManager.GetString("MusteriTanimlamaBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Telefon Numarası.
        /// </summary>
        internal static string MusteriTelefonNumarasi {
            get {
                return ResourceManager.GetString("MusteriTelefonNumarasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstenilen kriterlerde herhangi bir {0}kayıt bulunamamıştır..
        /// </summary>
        internal static string NoResult {
            get {
                return ResourceManager.GetString("NoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen oda bilgilerini kontrol ediniz.
        /// </summary>
        internal static string OdaBilgisiEksik {
            get {
                return ResourceManager.GetString("OdaBilgisiEksik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odadan Sorumlu Personel.
        /// </summary>
        internal static string OdadanSorumluPersonel {
            get {
                return ResourceManager.GetString("OdadanSorumluPersonel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı bir şekilde oda düzenlenmiştir.
        /// </summary>
        internal static string OdaDuzenlemeBasarili {
            get {
                return ResourceManager.GetString("OdaDuzenlemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı bir şekilde oda eklenmiştir.
        /// </summary>
        internal static string OdaEklemeBasarili {
            get {
                return ResourceManager.GetString("OdaEklemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı bir şekilde oda geri alınmıştır..
        /// </summary>
        internal static string odaGeriAlmaBasarili {
            get {
                return ResourceManager.GetString("odaGeriAlmaBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oda Grubu.
        /// </summary>
        internal static string OdaGrubu {
            get {
                return ResourceManager.GetString("OdaGrubu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oda Grubu:.
        /// </summary>
        internal static string OdaGrupLabel {
            get {
                return ResourceManager.GetString("OdaGrupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oda Kontrol.
        /// </summary>
        internal static string odaKontrol {
            get {
                return ResourceManager.GetString("odaKontrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oda Adı.
        /// </summary>
        internal static string OdaNumarasi {
            get {
                return ResourceManager.GetString("OdaNumarasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı bir şekilde oda silinmiştir.
        /// </summary>
        internal static string odaSilmeBasarili {
            get {
                return ResourceManager.GetString("odaSilmeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğün Ekle.
        /// </summary>
        internal static string ogunEkle {
            get {
                return ResourceManager.GetString("ogunEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğün Tanımlama.
        /// </summary>
        internal static string ogunTanimlama {
            get {
                return ResourceManager.GetString("ogunTanimlama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ölçülemedi.
        /// </summary>
        internal static string Olculemedi {
            get {
                return ResourceManager.GetString("Olculemedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen salon eklemek istediğiniz bloğa önce kat ekleyin veya bir kat seçin.
        /// </summary>
        internal static string onceKatEkleyiniz {
            get {
                return ResourceManager.GetString("onceKatEkleyiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı bir şekilde otel bilgileri sisteme eklenmiştir..
        /// </summary>
        internal static string otelBilgileriEklemeBasarili {
            get {
                return ResourceManager.GetString("otelBilgileriEklemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri.
        /// </summary>
        internal static string OzelMusteri {
            get {
                return ResourceManager.GetString("OzelMusteri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özel Yemek Ekle.
        /// </summary>
        internal static string ozelYemekEkle {
            get {
                return ResourceManager.GetString("ozelYemekEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel.
        /// </summary>
        internal static string Personel {
            get {
                return ResourceManager.GetString("Personel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Adı.
        /// </summary>
        internal static string personelAdi {
            get {
                return ResourceManager.GetString("personelAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel daha önceden tanımlanmış.
        /// </summary>
        internal static string personelDahaOncedenTanimlanmis {
            get {
                return ResourceManager.GetString("personelDahaOncedenTanimlanmis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Departmanı.
        /// </summary>
        internal static string personelDepartman {
            get {
                return ResourceManager.GetString("personelDepartman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı bir şekilde personel eklenmiştir.
        /// </summary>
        internal static string personelEklemeBasarili {
            get {
                return ResourceManager.GetString("personelEklemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı bir şekilde silinen personel geri alındı..
        /// </summary>
        internal static string PersonelGeriAlindi {
            get {
                return ResourceManager.GetString("PersonelGeriAlindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Görevlendir.
        /// </summary>
        internal static string personelGorevlendir {
            get {
                return ResourceManager.GetString("personelGorevlendir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı bir şekilde personel güncellenmiştir.
        /// </summary>
        internal static string personelGuncellemeBasarili {
            get {
                return ResourceManager.GetString("personelGuncellemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Kontrol.
        /// </summary>
        internal static string personelKontrol {
            get {
                return ResourceManager.GetString("personelKontrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Seç.
        /// </summary>
        internal static string personelSecimi {
            get {
                return ResourceManager.GetString("personelSecimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel silme işleminiz başarılı.
        /// </summary>
        internal static string personelSilmeBasarili {
            get {
                return ResourceManager.GetString("personelSilmeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Soyadı.
        /// </summary>
        internal static string personelSoyadi {
            get {
                return ResourceManager.GetString("personelSoyadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programa giriş yapan kullanıcı :.
        /// </summary>
        internal static string programaGirisYapanKullanici {
            get {
                return ResourceManager.GetString("programaGirisYapanKullanici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu program zaten çalışıyor.
        /// </summary>
        internal static string ProgramCalisiyorHata {
            get {
                return ResourceManager.GetString("ProgramCalisiyorHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programdan çıkış için emin misiniz?.
        /// </summary>
        internal static string ProgramCikisOnay {
            get {
                return ResourceManager.GetString("ProgramCikisOnay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervasyon işlemi başarı ile sonuçlanmıştır.
        /// </summary>
        internal static string RezervasyonBasarili {
            get {
                return ResourceManager.GetString("RezervasyonBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervasyon işlemi başarılı bir şekilde iptal edilmiştir..
        /// </summary>
        internal static string RezervasyonIptal {
            get {
                return ResourceManager.GetString("RezervasyonIptal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervasyon İptal Et.
        /// </summary>
        internal static string RezervasyoniptalEt {
            get {
                return ResourceManager.GetString("RezervasyoniptalEt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved Rooms.
        /// </summary>
        internal static string RezerveEdilmisOdalar {
            get {
                return ResourceManager.GetString("RezerveEdilmisOdalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önceden rezerve edilmiş oda bulunmamaktadır..
        /// </summary>
        internal static string rezerveOdalarBos {
            get {
                return ResourceManager.GetString("rezerveOdalarBos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saat.
        /// </summary>
        internal static string Saat {
            get {
                return ResourceManager.GetString("Saat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salon başarılı bir şekilde eklenmiştir..
        /// </summary>
        internal static string SalonEklemeBasarili {
            get {
                return ResourceManager.GetString("SalonEklemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salon ismi boş olamaz.
        /// </summary>
        internal static string salonIsmiBosGecilemez {
            get {
                return ResourceManager.GetString("salonIsmiBosGecilemez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen salon sorumlusu seçiniz.
        /// </summary>
        internal static string salonSorumlusuSeciniz {
            get {
                return ResourceManager.GetString("salonSorumlusuSeciniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıcaklık.
        /// </summary>
        internal static string Sicaklik {
            get {
                return ResourceManager.GetString("Sicaklik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        internal static string Sil {
            get {
                return ResourceManager.GetString("Sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen silinecek bloğu seçiniz..
        /// </summary>
        internal static string SilinecekBlokSec {
            get {
                return ResourceManager.GetString("SilinecekBlokSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen önce silinecek etkinliği seçiniz.
        /// </summary>
        internal static string silinecekEtkinlikSecin {
            get {
                return ResourceManager.GetString("silinecekEtkinlikSecin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen silinecek havuzu seçiniz.
        /// </summary>
        internal static string SilinecekHavuzSeciniz {
            get {
                return ResourceManager.GetString("SilinecekHavuzSeciniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen önce silinecek katı seçiniz.
        /// </summary>
        internal static string SilinecekKatSec {
            get {
                return ResourceManager.GetString("SilinecekKatSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen önce silinecek personeli seçiniz..
        /// </summary>
        internal static string silinecekPersonelSec {
            get {
                return ResourceManager.GetString("silinecekPersonelSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silinen Etkinliği Geri Al.
        /// </summary>
        internal static string SilinenEtkinligiGeriAl {
            get {
                return ResourceManager.GetString("SilinenEtkinligiGeriAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silinen Etkinlikleri Göster.
        /// </summary>
        internal static string SilinenEtkinlikleriGoster {
            get {
                return ResourceManager.GetString("SilinenEtkinlikleriGoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silinen havuz başarılı bir şekilde geri alınmıştır..
        /// </summary>
        internal static string SilinenHavuzGeriAlindi {
            get {
                return ResourceManager.GetString("SilinenHavuzGeriAlindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silinmiş Duyuruları Geri Al.
        /// </summary>
        internal static string silinmisDuyurulariGeriAl {
            get {
                return ResourceManager.GetString("silinmisDuyurulariGeriAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silinmiş Duyuruları Göster.
        /// </summary>
        internal static string silinmisDuyurulariGoster {
            get {
                return ResourceManager.GetString("silinmisDuyurulariGoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silinmiş Duyuruları Gösterme.
        /// </summary>
        internal static string SilinmisDuyurulariGosterme {
            get {
                return ResourceManager.GetString("SilinmisDuyurulariGosterme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silinmiş Kayıtları Geri Al.
        /// </summary>
        internal static string SilinmisKayitlariGeriAl {
            get {
                return ResourceManager.GetString("SilinmisKayitlariGeriAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silinmiş Kayıtları Göster.
        /// </summary>
        internal static string SilinmisKayitlariGoster {
            get {
                return ResourceManager.GetString("SilinmisKayitlariGoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silinmiş Kayıtları Gösterme.
        /// </summary>
        internal static string SilinmisKayitlariGosterme {
            get {
                return ResourceManager.GetString("SilinmisKayitlariGosterme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silinmiş odaları göster.
        /// </summary>
        internal static string silinmisOdalariGoster {
            get {
                return ResourceManager.GetString("silinmisOdalariGoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silinmiş Odaları Gösterme.
        /// </summary>
        internal static string silinmisOdalariGosterme {
            get {
                return ResourceManager.GetString("silinmisOdalariGosterme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silinmiş Odayı Geri Al.
        /// </summary>
        internal static string silinmisOdayiGeriAl {
            get {
                return ResourceManager.GetString("silinmisOdayiGeriAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silinmiş Personeli Geri Al.
        /// </summary>
        internal static string silinmisPersoneliGeriAl {
            get {
                return ResourceManager.GetString("silinmisPersoneliGeriAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silinmiş Personelleri Göster.
        /// </summary>
        internal static string silinmisPersonelleriGoster {
            get {
                return ResourceManager.GetString("silinmisPersonelleriGoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen silinecek duyuruyu seçiniz..
        /// </summary>
        internal static string SilmekicinDuyuruSec {
            get {
                return ResourceManager.GetString("SilmekicinDuyuruSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silmek için lütfen bir oda seçiniz ve ardından sil tuşuna basınız..
        /// </summary>
        internal static string silmekIcınOdaSec {
            get {
                return ResourceManager.GetString("silmekIcınOdaSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Gün.
        /// </summary>
        internal static string sonGun {
            get {
                return ResourceManager.GetString("sonGun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamam.
        /// </summary>
        internal static string Tamam {
            get {
                return ResourceManager.GetString("Tamam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen girdiğiniz tarih bilgilerini kontrol ediniz.
        /// </summary>
        internal static string TarihKontrol {
            get {
                return ResourceManager.GetString("TarihKontrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Tek Kişilik Yatak Bölümüne sadece rakam giriniz..
        /// </summary>
        internal static string tekKisilikRakamGir {
            get {
                return ResourceManager.GetString("tekKisilikRakamGir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tek Kişilik Yatak Sayısı.
        /// </summary>
        internal static string tekKisilikYatakSayisi {
            get {
                return ResourceManager.GetString("tekKisilikYatakSayisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temizlenme Tarihi.
        /// </summary>
        internal static string temizlenmeTarihi {
            get {
                return ResourceManager.GetString("temizlenmeTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı bir şekilde oda temizlenmiştir.
        /// </summary>
        internal static string temizlikBasarili {
            get {
                return ResourceManager.GetString("temizlikBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temizlik Yap.
        /// </summary>
        internal static string temizlikYap {
            get {
                return ResourceManager.GetString("temizlikYap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        internal static string tileAyarlar {
            get {
                return ResourceManager.GetString("tileAyarlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgilendirme Formu.
        /// </summary>
        internal static string tileBilgilendirmeFormu {
            get {
                return ResourceManager.GetString("tileBilgilendirmeFormu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blok Ekle.
        /// </summary>
        internal static string tileBlokEkle {
            get {
                return ResourceManager.GetString("tileBlokEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyuru İşlemleri.
        /// </summary>
        internal static string tileDuyuru {
            get {
                return ResourceManager.GetString("tileDuyuru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik İşlemleri.
        /// </summary>
        internal static string tileEtkinlik {
            get {
                return ResourceManager.GetString("tileEtkinlik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oto Gece Modu.
        /// </summary>
        internal static string tileGeceModu {
            get {
                return ResourceManager.GetString("tileGeceModu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Havuz Ekle.
        /// </summary>
        internal static string tileHavuzEkle {
            get {
                return ResourceManager.GetString("tileHavuzEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri tanımlama.
        /// </summary>
        internal static string tileItemMusteriTanimlama {
            get {
                return ResourceManager.GetString("tileItemMusteriTanimlama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Tanımlamaları.
        /// </summary>
        internal static string tileKategoriTanimlamalari {
            get {
                return ResourceManager.GetString("tileKategoriTanimlamalari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kat Ekle.
        /// </summary>
        internal static string tileKatEkle {
            get {
                return ResourceManager.GetString("tileKatEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Tercihleri.
        /// </summary>
        internal static string tileKullaniciTercihleri {
            get {
                return ResourceManager.GetString("tileKullaniciTercihleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisans İşlemleri.
        /// </summary>
        internal static string tileLisans {
            get {
                return ResourceManager.GetString("tileLisans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri İşlemleri.
        /// </summary>
        internal static string tileMusteri {
            get {
                return ResourceManager.GetString("tileMusteri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oda İşlemleri.
        /// </summary>
        internal static string tileOda {
            get {
                return ResourceManager.GetString("tileOda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oda Check-in.
        /// </summary>
        internal static string tileOdaCheckin {
            get {
                return ResourceManager.GetString("tileOdaCheckin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oda Listesi.
        /// </summary>
        internal static string tileOdaListesi {
            get {
                return ResourceManager.GetString("tileOdaListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oda Rezerve Et.
        /// </summary>
        internal static string tileOdaRezerveEt {
            get {
                return ResourceManager.GetString("tileOdaRezerveEt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oda Tanımlama.
        /// </summary>
        internal static string tileOdaTanimlama {
            get {
                return ResourceManager.GetString("tileOdaTanimlama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay Formu.
        /// </summary>
        internal static string tileOnayForm {
            get {
                return ResourceManager.GetString("tileOnayForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otel Tanımlamaları.
        /// </summary>
        internal static string tileOtelTanimlamalari {
            get {
                return ResourceManager.GetString("tileOtelTanimlamalari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel İşlemleri.
        /// </summary>
        internal static string tilePersonel {
            get {
                return ResourceManager.GetString("tilePersonel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Listesi.
        /// </summary>
        internal static string tilePersonelListesi {
            get {
                return ResourceManager.GetString("tilePersonelListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Oluştur.
        /// </summary>
        internal static string tilePersonelOlustur {
            get {
                return ResourceManager.GetString("tilePersonelOlustur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renk Değiştir.
        /// </summary>
        internal static string tileRenkDegistir {
            get {
                return ResourceManager.GetString("tileRenkDegistir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salon Tanımlamaları.
        /// </summary>
        internal static string tileSalonTanimlamalari {
            get {
                return ResourceManager.GetString("tileSalonTanimlamalari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıcaklık Bilgileri.
        /// </summary>
        internal static string tileSicaklik {
            get {
                return ResourceManager.GetString("tileSicaklik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Süre Uzat.
        /// </summary>
        internal static string tileSureUzat {
            get {
                return ResourceManager.GetString("tileSureUzat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temizlik İşlemleri.
        /// </summary>
        internal static string tileTemizlik {
            get {
                return ResourceManager.GetString("tileTemizlik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplantı İşlemleri.
        /// </summary>
        internal static string tileToplanti {
            get {
                return ResourceManager.GetString("tileToplanti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplantı Listesi.
        /// </summary>
        internal static string tileToplantiListesi {
            get {
                return ResourceManager.GetString("tileToplantiListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplantı Oluştur.
        /// </summary>
        internal static string tileToplantiOlustur {
            get {
                return ResourceManager.GetString("tileToplantiOlustur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yemek İşlemleri.
        /// </summary>
        internal static string tileYemek {
            get {
                return ResourceManager.GetString("tileYemek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yemek Listesi.
        /// </summary>
        internal static string tileYemekListesi {
            get {
                return ResourceManager.GetString("tileYemekListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetki İşlemleri.
        /// </summary>
        internal static string tileYetki {
            get {
                return ResourceManager.GetString("tileYetki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı bir şekilde toplantı eklenmiştir..
        /// </summary>
        internal static string ToplantiEklemeBasarili {
            get {
                return ResourceManager.GetString("ToplantiEklemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Bilgileri Göster.
        /// </summary>
        internal static string tumBilgileriGoster {
            get {
                return ResourceManager.GetString("tumBilgileriGoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tümü.
        /// </summary>
        internal static string Tümü {
            get {
                return ResourceManager.GetString("Tümü", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yardım.
        /// </summary>
        internal static string Yardim {
            get {
                return ResourceManager.GetString("Yardim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yemek Adı.
        /// </summary>
        internal static string yemekAdi {
            get {
                return ResourceManager.GetString("yemekAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yemek adı boş olamaz.
        /// </summary>
        internal static string yemekAdiBosGecilemez {
            get {
                return ResourceManager.GetString("yemekAdiBosGecilemez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı bir şekilde yemek eklenmiştir.
        /// </summary>
        internal static string yemekEklemeBasarili {
            get {
                return ResourceManager.GetString("yemekEklemeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yemek Salonu.
        /// </summary>
        internal static string yemekSalonu {
            get {
                return ResourceManager.GetString("yemekSalonu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı bir şekilde yemek silinmiştir.
        /// </summary>
        internal static string yemekSilmeBasarili {
            get {
                return ResourceManager.GetString("yemekSilmeBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yemek Türü.
        /// </summary>
        internal static string yemekTuru {
            get {
                return ResourceManager.GetString("yemekTuru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarılı bir şekilde personel yetkisi güncellenmiştir.
        /// </summary>
        internal static string YetkiGuncellemeBasarili {
            get {
                return ResourceManager.GetString("YetkiGuncellemeBasarili", resourceCulture);
            }
        }
    }
}
